# Generated by Django 3.1.4 on 2021-01-07 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrolled',
            old_name='Attendance',
            new_name='classesAttended',
        ),
    ]
